@url = https://qienrar5kj.execute-api.eu-west-1.amazonaws.com/prod/

GET {{url}}/empl?id=15e39cf8-1713-465c-b3c1-fc86471cd90a
###

POST {{url}}/empl
content-type: application/json

 {
    "name": "John",
    "possition": "enginner"
 }
###